-- =====================================================================
-- Nexovo Hospitality POS — Phase 1 — Oracle schema (19c+ / 21c / 23ai)
-- Run as the application schema owner (e.g. POS_APP).
-- =====================================================================
SET DEFINE OFF;

-- ---------------------------------------------------------------------
-- Tenancy / organisation
-- ---------------------------------------------------------------------
CREATE TABLE branches (
  branch_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_code          VARCHAR2(20)  NOT NULL,
  business_name        VARCHAR2(150) NOT NULL,
  branch_name          VARCHAR2(150) NOT NULL,
  address_line         VARCHAR2(400),
  city                 VARCHAR2(100),
  phone                VARCHAR2(30),
  email                VARCHAR2(150),
  gst_number           VARCHAR2(30),
  logo_url             VARCHAR2(500),
  welcome_message      VARCHAR2(300),
  currency_code        VARCHAR2(3)   DEFAULT 'INR' NOT NULL,
  timezone             VARCHAR2(60)  DEFAULT 'Asia/Kolkata' NOT NULL,
  service_charge_pct   NUMBER(5,2)   DEFAULT 0 NOT NULL,
  tax_on_service_chg   CHAR(1)       DEFAULT 'N' NOT NULL,
  rounding_mode        VARCHAR2(10)  DEFAULT 'NEAREST' NOT NULL,
  allow_multi_orders   CHAR(1)       DEFAULT 'N' NOT NULL,
  receipt_footer       VARCHAR2(300) DEFAULT 'Thank you, visit again!',
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_branches_code       UNIQUE (branch_code),
  CONSTRAINT ck_branches_sc_pct     CHECK (service_charge_pct BETWEEN 0 AND 100),
  CONSTRAINT ck_branches_flags      CHECK (tax_on_service_chg IN ('Y','N') AND allow_multi_orders IN ('Y','N') AND is_active IN ('Y','N')),
  CONSTRAINT ck_branches_rounding   CHECK (rounding_mode IN ('NEAREST','UP','DOWN','NONE'))
);

-- ---------------------------------------------------------------------
-- Security
-- ---------------------------------------------------------------------
CREATE TABLE roles (
  role_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  role_code            VARCHAR2(30)  NOT NULL,
  role_name            VARCHAR2(80)  NOT NULL,
  description          VARCHAR2(300),
  max_discount_pct     NUMBER(5,2)   DEFAULT 0 NOT NULL,
  is_system            CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_roles_code UNIQUE (role_code),
  CONSTRAINT ck_roles_disc CHECK (max_discount_pct BETWEEN 0 AND 100)
);

CREATE TABLE permissions (
  permission_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  permission_code      VARCHAR2(60)  NOT NULL,
  module_name          VARCHAR2(40)  NOT NULL,
  description          VARCHAR2(200),
  CONSTRAINT uq_permissions_code UNIQUE (permission_code)
);

CREATE TABLE role_permissions (
  role_id              NUMBER NOT NULL,
  permission_id        NUMBER NOT NULL,
  CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions(permission_id)
);

CREATE TABLE users (
  user_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  username             VARCHAR2(60)  NOT NULL,
  email                VARCHAR2(150),
  full_name            VARCHAR2(150) NOT NULL,
  phone                VARCHAR2(30),
  password_hash        RAW(64)       NOT NULL,
  password_salt        RAW(32)       NOT NULL,
  approval_pin_hash    RAW(64),
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  failed_logins        NUMBER(3)     DEFAULT 0 NOT NULL,
  locked_until         TIMESTAMP,
  last_login_at        TIMESTAMP,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT fk_users_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_users_flags CHECK (is_active IN ('Y','N') AND is_deleted IN ('Y','N'))
);
CREATE UNIQUE INDEX uq_users_email ON users (LOWER(email));

CREATE TABLE user_roles (
  user_id              NUMBER NOT NULL,
  role_id              NUMBER NOT NULL,
  assigned_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  assigned_by          NUMBER,
  CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE user_sessions (
  session_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id              NUMBER        NOT NULL,
  token_hash           RAW(64)       NOT NULL,
  issued_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at           TIMESTAMP     NOT NULL,
  revoked_at           TIMESTAMP,
  ip_address           VARCHAR2(60),
  user_agent           VARCHAR2(400),
  CONSTRAINT uq_sessions_token UNIQUE (token_hash),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
CREATE INDEX ix_sessions_user ON user_sessions (user_id, expires_at);

-- ---------------------------------------------------------------------
-- Layout: floors & tables
-- ---------------------------------------------------------------------
CREATE TABLE floors (
  floor_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  floor_code           VARCHAR2(20)  NOT NULL,
  floor_name           VARCHAR2(100) NOT NULL,
  display_order        NUMBER(4)     DEFAULT 0 NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_floors_code UNIQUE (branch_id, floor_code),
  CONSTRAINT fk_floors_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_floors_flags CHECK (is_active IN ('Y','N') AND is_deleted IN ('Y','N'))
);

CREATE TABLE dining_tables (
  table_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  floor_id             NUMBER        NOT NULL,
  table_number         VARCHAR2(20)  NOT NULL,
  table_name           VARCHAR2(60)  NOT NULL,
  seating_capacity     NUMBER(3)     DEFAULT 4 NOT NULL,
  public_code          VARCHAR2(32)  NOT NULL,      -- opaque token used in QR URL
  qr_version           NUMBER(5)     DEFAULT 1 NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'AVAILABLE' NOT NULL,
  status_override      CHAR(1)       DEFAULT 'N' NOT NULL, -- Y = manually set, not derived
  assigned_waiter_id   NUMBER,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_tables_number UNIQUE (branch_id, table_number),
  CONSTRAINT uq_tables_public UNIQUE (public_code),
  CONSTRAINT fk_tables_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_tables_floor  FOREIGN KEY (floor_id)  REFERENCES floors(floor_id),
  CONSTRAINT fk_tables_waiter FOREIGN KEY (assigned_waiter_id) REFERENCES users(user_id),
  CONSTRAINT ck_tables_capacity CHECK (seating_capacity > 0),
  CONSTRAINT ck_tables_status CHECK (status IN ('AVAILABLE','OCCUPIED','ORDERING','PREPARING','READY','BILLING','PAYMENT_PENDING','CLOSED')),
  CONSTRAINT ck_tables_flags CHECK (status_override IN ('Y','N') AND is_active IN ('Y','N') AND is_deleted IN ('Y','N'))
);
CREATE INDEX ix_tables_floor ON dining_tables (floor_id);
CREATE INDEX ix_tables_waiter ON dining_tables (assigned_waiter_id);

-- ---------------------------------------------------------------------
-- Tax configuration
-- ---------------------------------------------------------------------
CREATE TABLE tax_configurations (
  tax_group_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  tax_code             VARCHAR2(20)  NOT NULL,
  tax_name             VARCHAR2(80)  NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_tax_code UNIQUE (branch_id, tax_code),
  CONSTRAINT fk_tax_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_tax_flags CHECK (is_active IN ('Y','N'))
);

CREATE TABLE tax_components (
  tax_component_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  tax_group_id         NUMBER        NOT NULL,
  component_code       VARCHAR2(20)  NOT NULL,   -- CGST / SGST / IGST / VAT / CESS
  component_name       VARCHAR2(80)  NOT NULL,
  rate_pct             NUMBER(6,3)   NOT NULL,
  CONSTRAINT uq_tax_comp UNIQUE (tax_group_id, component_code),
  CONSTRAINT fk_tax_comp_group FOREIGN KEY (tax_group_id) REFERENCES tax_configurations(tax_group_id),
  CONSTRAINT ck_tax_comp_rate CHECK (rate_pct >= 0)
);

-- ---------------------------------------------------------------------
-- Menu
-- ---------------------------------------------------------------------
CREATE TABLE menu_categories (
  category_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  category_name        VARCHAR2(100) NOT NULL,
  slug                 VARCHAR2(100) NOT NULL,
  description          VARCHAR2(300),
  image_url            VARCHAR2(500),
  default_prep_loc     VARCHAR2(10)  DEFAULT 'KITCHEN' NOT NULL,
  display_order        NUMBER(4)     DEFAULT 0 NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_cat_slug UNIQUE (branch_id, slug),
  CONSTRAINT fk_cat_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_cat_prep CHECK (default_prep_loc IN ('KITCHEN','BAR')),
  CONSTRAINT ck_cat_flags CHECK (is_active IN ('Y','N') AND is_deleted IN ('Y','N'))
);

CREATE TABLE menu_items (
  item_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  category_id          NUMBER        NOT NULL,
  item_code            VARCHAR2(30)  NOT NULL,
  item_name            VARCHAR2(150) NOT NULL,
  description          VARCHAR2(600),
  image_url            VARCHAR2(500),
  current_price        NUMBER(12,2)  NOT NULL,
  prep_location        VARCHAR2(10)  NOT NULL,
  tax_group_id         NUMBER        NOT NULL,
  is_veg               CHAR(1)       DEFAULT 'N' NOT NULL,
  is_popular           CHAR(1)       DEFAULT 'N' NOT NULL,
  is_available         CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  display_order        NUMBER(4)     DEFAULT 0 NOT NULL,
  tags                 VARCHAR2(300),
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_items_code UNIQUE (branch_id, item_code),
  CONSTRAINT fk_items_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_items_cat FOREIGN KEY (category_id) REFERENCES menu_categories(category_id),
  CONSTRAINT fk_items_tax FOREIGN KEY (tax_group_id) REFERENCES tax_configurations(tax_group_id),
  CONSTRAINT ck_items_price CHECK (current_price >= 0),
  CONSTRAINT ck_items_prep CHECK (prep_location IN ('KITCHEN','BAR')),
  CONSTRAINT ck_items_flags CHECK (is_veg IN ('Y','N') AND is_popular IN ('Y','N') AND is_available IN ('Y','N') AND is_active IN ('Y','N') AND is_deleted IN ('Y','N'))
);
CREATE INDEX ix_items_cat ON menu_items (category_id, display_order);

-- price history (append only)
CREATE TABLE menu_item_prices (
  price_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  item_id              NUMBER        NOT NULL,
  price                NUMBER(12,2)  NOT NULL,
  effective_from       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  effective_to         TIMESTAMP,
  created_by           NUMBER,
  CONSTRAINT fk_prices_item FOREIGN KEY (item_id) REFERENCES menu_items(item_id),
  CONSTRAINT ck_prices_val CHECK (price >= 0)
);
CREATE INDEX ix_prices_item ON menu_item_prices (item_id, effective_from);

-- ---------------------------------------------------------------------
-- Offers
-- ---------------------------------------------------------------------
CREATE TABLE offers (
  offer_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  offer_name           VARCHAR2(120) NOT NULL,
  description          VARCHAR2(400),
  offer_type           VARCHAR2(20)  NOT NULL,   -- PERCENTAGE FLAT BOGO COMBO HAPPY_HOUR
  discount_value       NUMBER(12,2)  DEFAULT 0 NOT NULL,
  max_discount_amt     NUMBER(12,2),
  applies_to           VARCHAR2(12)  DEFAULT 'ALL' NOT NULL, -- ALL CATEGORIES ITEMS
  start_date           DATE          NOT NULL,
  end_date             DATE          NOT NULL,
  start_time           VARCHAR2(5),              -- 'HH24:MI'
  end_time             VARCHAR2(5),
  days_of_week         VARCHAR2(20),             -- '1,2,3' (1=Mon) null = all
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT fk_offers_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_offers_type CHECK (offer_type IN ('PERCENTAGE','FLAT','BOGO','COMBO','HAPPY_HOUR')),
  CONSTRAINT ck_offers_applies CHECK (applies_to IN ('ALL','CATEGORIES','ITEMS')),
  CONSTRAINT ck_offers_dates CHECK (end_date >= start_date),
  CONSTRAINT ck_offers_value CHECK (discount_value >= 0),
  CONSTRAINT ck_offers_flags CHECK (is_active IN ('Y','N') AND is_deleted IN ('Y','N'))
);

CREATE TABLE offer_rules (
  offer_rule_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  offer_id             NUMBER        NOT NULL,
  rule_type            VARCHAR2(12)  NOT NULL,   -- CATEGORY | ITEM
  category_id          NUMBER,
  item_id              NUMBER,
  CONSTRAINT fk_rules_offer FOREIGN KEY (offer_id) REFERENCES offers(offer_id),
  CONSTRAINT fk_rules_cat FOREIGN KEY (category_id) REFERENCES menu_categories(category_id),
  CONSTRAINT fk_rules_item FOREIGN KEY (item_id) REFERENCES menu_items(item_id),
  CONSTRAINT ck_rules_type CHECK ((rule_type = 'CATEGORY' AND category_id IS NOT NULL AND item_id IS NULL)
                               OR (rule_type = 'ITEM' AND item_id IS NOT NULL AND category_id IS NULL))
);
CREATE INDEX ix_rules_offer ON offer_rules (offer_id);

-- ---------------------------------------------------------------------
-- Document numbering (concurrency safe)
-- ---------------------------------------------------------------------
CREATE TABLE doc_sequences (
  doc_type             VARCHAR2(10)  NOT NULL,   -- ORD BILL PAY KOT BOT
  seq_date             DATE          NOT NULL,
  last_no              NUMBER(8)     DEFAULT 0 NOT NULL,
  CONSTRAINT pk_doc_sequences PRIMARY KEY (doc_type, seq_date)
);

-- ---------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------
CREATE TABLE orders (
  order_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_number         VARCHAR2(30)  NOT NULL,
  branch_id            NUMBER        NOT NULL,
  table_id             NUMBER        NOT NULL,
  waiter_id            NUMBER        NOT NULL,
  order_type           VARCHAR2(20)  DEFAULT 'DINE_IN' NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'DRAFT' NOT NULL,
  guest_count          NUMBER(3)     DEFAULT 1,
  notes                VARCHAR2(500),
  subtotal             NUMBER(12,2)  DEFAULT 0 NOT NULL,   -- cached Σ active lines
  reference_type       VARCHAR2(30),                       -- Phase-2: ROOM, RESERVATION …
  reference_id         NUMBER,
  confirmed_at         TIMESTAMP,
  bill_requested_at    TIMESTAMP,
  completed_at         TIMESTAMP,
  cancelled_at         TIMESTAMP,
  cancelled_by         NUMBER,
  cancel_reason        VARCHAR2(300),
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_orders_number UNIQUE (order_number),
  CONSTRAINT fk_orders_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_orders_table  FOREIGN KEY (table_id)  REFERENCES dining_tables(table_id),
  CONSTRAINT fk_orders_waiter FOREIGN KEY (waiter_id) REFERENCES users(user_id),
  CONSTRAINT ck_orders_status CHECK (status IN ('DRAFT','CONFIRMED','IN_PROGRESS','PARTIALLY_READY','READY','SERVED','BILL_REQUESTED','BILLED','PAID','COMPLETED','CANCELLED')),
  CONSTRAINT ck_orders_type CHECK (order_type IN ('DINE_IN','TAKEAWAY','ROOM_SERVICE','DELIVERY'))
);
CREATE INDEX ix_orders_table_status ON orders (table_id, status);
CREATE INDEX ix_orders_status ON orders (branch_id, status);
CREATE INDEX ix_orders_created ON orders (branch_id, created_at);
CREATE INDEX ix_orders_waiter ON orders (waiter_id);
-- Rule 2: one active order per table (unless branch allows multiples — enforced in ORDER_PKG)
CREATE UNIQUE INDEX uq_orders_active_table ON orders (
  CASE WHEN status NOT IN ('COMPLETED','CANCELLED') THEN table_id END
);

CREATE TABLE order_items (
  order_item_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id             NUMBER        NOT NULL,
  item_id              NUMBER        NOT NULL,
  batch_no             NUMBER(4)     DEFAULT 1 NOT NULL,
  item_name            VARCHAR2(150) NOT NULL,   -- snapshot (Rule 4)
  unit_price           NUMBER(12,2)  NOT NULL,   -- snapshot (Rule 4)
  quantity             NUMBER(6,2)   NOT NULL,
  line_total           NUMBER(12,2)  NOT NULL,
  prep_location        VARCHAR2(10)  NOT NULL,
  tax_group_id         NUMBER        NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'NEW' NOT NULL,
  notes                VARCHAR2(300),
  added_at             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  started_at           TIMESTAMP,
  ready_at             TIMESTAMP,
  served_at            TIMESTAMP,
  cancelled_at         TIMESTAMP,
  cancelled_by         NUMBER,
  approved_by          NUMBER,
  cancel_reason        VARCHAR2(300),
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_oi_item  FOREIGN KEY (item_id)  REFERENCES menu_items(item_id),
  CONSTRAINT fk_oi_tax   FOREIGN KEY (tax_group_id) REFERENCES tax_configurations(tax_group_id),
  CONSTRAINT ck_oi_qty   CHECK (quantity > 0),
  CONSTRAINT ck_oi_price CHECK (unit_price >= 0 AND line_total >= 0),
  CONSTRAINT ck_oi_prep  CHECK (prep_location IN ('KITCHEN','BAR')),
  CONSTRAINT ck_oi_status CHECK (status IN ('NEW','PREPARING','READY','SERVED','CANCELLED'))
);
CREATE INDEX ix_oi_order ON order_items (order_id);
CREATE INDEX ix_oi_loc_status ON order_items (prep_location, status);

CREATE TABLE order_status_history (
  history_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_id             NUMBER        NOT NULL,
  from_status          VARCHAR2(20),
  to_status            VARCHAR2(20)  NOT NULL,
  changed_by           NUMBER,
  changed_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  note                 VARCHAR2(300),
  CONSTRAINT fk_osh_order FOREIGN KEY (order_id) REFERENCES orders(order_id)
);
CREATE INDEX ix_osh_order ON order_status_history (order_id, changed_at);

CREATE TABLE order_item_status_history (
  history_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  order_item_id        NUMBER        NOT NULL,
  from_status          VARCHAR2(20),
  to_status            VARCHAR2(20)  NOT NULL,
  changed_by           NUMBER,
  changed_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_oish_item FOREIGN KEY (order_item_id) REFERENCES order_items(order_item_id)
);
CREATE INDEX ix_oish_item ON order_item_status_history (order_item_id);

-- Tickets: one per (order, batch, location). Items link back via order_items.ticket_id-like join table
CREATE TABLE kitchen_tickets (
  ticket_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  ticket_number        VARCHAR2(30)  NOT NULL,
  order_id             NUMBER        NOT NULL,
  batch_no             NUMBER(4)     NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'NEW' NOT NULL,   -- derived: NEW PREPARING READY SERVED CANCELLED
  printed_at           TIMESTAMP,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  CONSTRAINT uq_kt_number UNIQUE (ticket_number),
  CONSTRAINT uq_kt_batch UNIQUE (order_id, batch_no),
  CONSTRAINT fk_kt_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT ck_kt_status CHECK (status IN ('NEW','PREPARING','READY','SERVED','CANCELLED'))
);

CREATE TABLE bar_tickets (
  ticket_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  ticket_number        VARCHAR2(30)  NOT NULL,
  order_id             NUMBER        NOT NULL,
  batch_no             NUMBER(4)     NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'NEW' NOT NULL,
  printed_at           TIMESTAMP,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  CONSTRAINT uq_bt_number UNIQUE (ticket_number),
  CONSTRAINT uq_bt_batch UNIQUE (order_id, batch_no),
  CONSTRAINT fk_bt_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT ck_bt_status CHECK (status IN ('NEW','PREPARING','READY','SERVED','CANCELLED'))
);

-- ---------------------------------------------------------------------
-- Billing
-- ---------------------------------------------------------------------
CREATE TABLE bills (
  bill_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  bill_number          VARCHAR2(30)  NOT NULL,
  branch_id            NUMBER        NOT NULL,
  order_id             NUMBER        NOT NULL,
  cashier_id           NUMBER        NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL,      -- OPEN FINALIZED PAID CLOSED VOID
  payment_status       VARCHAR2(20)  DEFAULT 'UNPAID' NOT NULL,    -- UNPAID PARTIALLY_PAID PAID REFUNDED
  subtotal             NUMBER(12,2)  DEFAULT 0 NOT NULL,
  item_discount_total  NUMBER(12,2)  DEFAULT 0 NOT NULL,
  order_discount_total NUMBER(12,2)  DEFAULT 0 NOT NULL,
  service_charge_pct   NUMBER(5,2)   DEFAULT 0 NOT NULL,
  service_charge_amt   NUMBER(12,2)  DEFAULT 0 NOT NULL,
  tax_total            NUMBER(12,2)  DEFAULT 0 NOT NULL,
  round_off            NUMBER(6,2)   DEFAULT 0 NOT NULL,
  grand_total          NUMBER(12,2)  DEFAULT 0 NOT NULL,
  paid_amount          NUMBER(12,2)  DEFAULT 0 NOT NULL,
  notes                VARCHAR2(400),
  finalized_at         TIMESTAMP,
  paid_at              TIMESTAMP,
  closed_at            TIMESTAMP,
  voided_at            TIMESTAMP,
  void_reason          VARCHAR2(300),
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_bills_number UNIQUE (bill_number),
  CONSTRAINT fk_bills_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_bills_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_bills_cashier FOREIGN KEY (cashier_id) REFERENCES users(user_id),
  CONSTRAINT ck_bills_status CHECK (status IN ('OPEN','FINALIZED','PAID','CLOSED','VOID')),
  CONSTRAINT ck_bills_pstatus CHECK (payment_status IN ('UNPAID','PARTIALLY_PAID','PAID','REFUNDED')),
  CONSTRAINT ck_bills_amounts CHECK (subtotal >= 0 AND grand_total >= 0 AND paid_amount >= 0)
);
CREATE INDEX ix_bills_order ON bills (order_id);
CREATE INDEX ix_bills_status ON bills (branch_id, status, payment_status);
CREATE INDEX ix_bills_created ON bills (branch_id, created_at);
CREATE UNIQUE INDEX uq_bills_open_order ON bills (CASE WHEN status <> 'VOID' THEN order_id END);

CREATE TABLE bill_items (
  bill_item_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  bill_id              NUMBER        NOT NULL,
  order_item_id        NUMBER        NOT NULL,
  item_name            VARCHAR2(150) NOT NULL,
  quantity             NUMBER(6,2)   NOT NULL,
  unit_price           NUMBER(12,2)  NOT NULL,
  line_total           NUMBER(12,2)  NOT NULL,
  discount_amount      NUMBER(12,2)  DEFAULT 0 NOT NULL,   -- item-level (offer)
  taxable_amount       NUMBER(12,2)  DEFAULT 0 NOT NULL,
  tax_group_id         NUMBER        NOT NULL,
  tax_pct              NUMBER(6,3)   DEFAULT 0 NOT NULL,
  tax_amount           NUMBER(12,2)  DEFAULT 0 NOT NULL,
  offer_id             NUMBER,
  CONSTRAINT fk_bi_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
  CONSTRAINT fk_bi_oi FOREIGN KEY (order_item_id) REFERENCES order_items(order_item_id),
  CONSTRAINT fk_bi_tax FOREIGN KEY (tax_group_id) REFERENCES tax_configurations(tax_group_id),
  CONSTRAINT fk_bi_offer FOREIGN KEY (offer_id) REFERENCES offers(offer_id),
  CONSTRAINT ck_bi_amounts CHECK (quantity > 0 AND unit_price >= 0 AND discount_amount >= 0)
);
CREATE INDEX ix_bi_bill ON bill_items (bill_id);

CREATE TABLE bill_taxes (
  bill_tax_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  bill_id              NUMBER        NOT NULL,
  component_code       VARCHAR2(20)  NOT NULL,
  component_name       VARCHAR2(80)  NOT NULL,
  rate_pct             NUMBER(6,3)   NOT NULL,
  taxable_amount       NUMBER(12,2)  NOT NULL,
  tax_amount           NUMBER(12,2)  NOT NULL,
  CONSTRAINT fk_btx_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id)
);
CREATE INDEX ix_btx_bill ON bill_taxes (bill_id);

CREATE TABLE discounts (
  discount_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  bill_id              NUMBER        NOT NULL,
  discount_type        VARCHAR2(20)  NOT NULL,   -- PERCENTAGE FLAT OFFER
  discount_value       NUMBER(12,2)  NOT NULL,
  discount_amount      NUMBER(12,2)  NOT NULL,
  reason               VARCHAR2(300) NOT NULL,
  offer_id             NUMBER,
  applied_by           NUMBER        NOT NULL,
  approved_by          NUMBER,
  is_voided            CHAR(1)       DEFAULT 'N' NOT NULL,
  voided_at            TIMESTAMP,
  voided_by            NUMBER,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_disc_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
  CONSTRAINT fk_disc_offer FOREIGN KEY (offer_id) REFERENCES offers(offer_id),
  CONSTRAINT fk_disc_applied FOREIGN KEY (applied_by) REFERENCES users(user_id),
  CONSTRAINT fk_disc_approved FOREIGN KEY (approved_by) REFERENCES users(user_id),
  CONSTRAINT ck_disc_type CHECK (discount_type IN ('PERCENTAGE','FLAT','OFFER')),
  CONSTRAINT ck_disc_amounts CHECK (discount_value >= 0 AND discount_amount >= 0),
  CONSTRAINT ck_disc_void CHECK (is_voided IN ('Y','N'))
);
CREATE INDEX ix_disc_bill ON discounts (bill_id);

-- ---------------------------------------------------------------------
-- Payments (separate from bills, never deleted — Rule 7)
-- ---------------------------------------------------------------------
CREATE TABLE payments (
  payment_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  payment_number       VARCHAR2(30)  NOT NULL,
  bill_id              NUMBER        NOT NULL,
  payment_method       VARCHAR2(20)  NOT NULL,   -- CASH UPI CARD COMPLIMENTARY (lookup, extensible)
  amount               NUMBER(12,2)  NOT NULL,
  reference_no         VARCHAR2(100),
  status               VARCHAR2(20)  DEFAULT 'SUCCESS' NOT NULL,   -- SUCCESS REVERSED
  received_by          NUMBER        NOT NULL,
  received_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  reversed_at          TIMESTAMP,
  reversed_by          NUMBER,
  reversal_reason      VARCHAR2(300),
  CONSTRAINT uq_pay_number UNIQUE (payment_number),
  CONSTRAINT fk_pay_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
  CONSTRAINT fk_pay_user FOREIGN KEY (received_by) REFERENCES users(user_id),
  CONSTRAINT ck_pay_amount CHECK (amount > 0),
  CONSTRAINT ck_pay_status CHECK (status IN ('SUCCESS','REVERSED'))
);
CREATE INDEX ix_pay_bill ON payments (bill_id);
CREATE INDEX ix_pay_received ON payments (received_at);

-- Gateway / device level transactions (Phase-1: manual entries; Phase-2: PG callbacks)
CREATE TABLE payment_transactions (
  txn_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  payment_id           NUMBER        NOT NULL,
  txn_type             VARCHAR2(20)  NOT NULL,   -- CAPTURE REVERSAL REFUND
  gateway              VARCHAR2(40),
  gateway_txn_id       VARCHAR2(120),
  amount               NUMBER(12,2)  NOT NULL,
  status               VARCHAR2(20)  NOT NULL,   -- SUCCESS FAILED PENDING
  raw_payload          CLOB,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  CONSTRAINT fk_ptx_payment FOREIGN KEY (payment_id) REFERENCES payments(payment_id),
  CONSTRAINT ck_ptx_type CHECK (txn_type IN ('CAPTURE','REVERSAL','REFUND')),
  CONSTRAINT ck_ptx_status CHECK (status IN ('SUCCESS','FAILED','PENDING'))
);
CREATE INDEX ix_ptx_payment ON payment_transactions (payment_id);

-- ---------------------------------------------------------------------
-- Audit & events
-- ---------------------------------------------------------------------
CREATE TABLE audit_logs (
  audit_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER,
  user_id              NUMBER,
  action_code          VARCHAR2(60)  NOT NULL,
  entity_name          VARCHAR2(60)  NOT NULL,
  entity_id            NUMBER,
  old_value            CLOB,
  new_value            CLOB,
  ip_address           VARCHAR2(60),
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_audit_entity ON audit_logs (entity_name, entity_id);
CREATE INDEX ix_audit_created ON audit_logs (created_at);

-- Real-time event outbox consumed by /events polling (or pushed by a future SSE bridge)
CREATE TABLE realtime_events (
  event_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  topic                VARCHAR2(40)  NOT NULL,   -- orders tables kitchen bar bills menu
  event_type           VARCHAR2(60)  NOT NULL,
  entity_id            NUMBER,
  payload              CLOB,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_events_created ON realtime_events (branch_id, created_at);

-- ---------------------------------------------------------------------
-- Views (read models)
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW v_active_orders AS
SELECT o.order_id, o.order_number, o.branch_id, o.table_id, t.table_name, t.table_number,
       f.floor_name, o.waiter_id, u.full_name AS waiter_name, o.status, o.subtotal,
       o.guest_count, o.notes, o.created_at, o.confirmed_at, o.bill_requested_at,
       (SELECT COUNT(*) FROM order_items oi WHERE oi.order_id = o.order_id AND oi.status <> 'CANCELLED') AS item_count
FROM orders o
JOIN dining_tables t ON t.table_id = o.table_id
JOIN floors f ON f.floor_id = t.floor_id
JOIN users u ON u.user_id = o.waiter_id
WHERE o.status NOT IN ('COMPLETED','CANCELLED');

CREATE OR REPLACE VIEW v_user_permissions AS
SELECT DISTINCT ur.user_id, p.permission_code
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.permission_id = rp.permission_id;

CREATE OR REPLACE VIEW v_offer_active AS
SELECT o.*,
       CASE WHEN o.is_active = 'Y' AND o.is_deleted = 'N'
             AND TRUNC(SYSDATE) BETWEEN o.start_date AND o.end_date
             AND (o.start_time IS NULL OR TO_CHAR(SYSDATE,'HH24:MI') >= o.start_time)
             AND (o.end_time   IS NULL OR TO_CHAR(SYSDATE,'HH24:MI') <= o.end_time)
             AND (o.days_of_week IS NULL OR INSTR(','||o.days_of_week||',', ','||TO_CHAR(SYSDATE,'ID')||',') > 0)  -- ISO weekday: 1 = Monday
            THEN 'Y' ELSE 'N' END AS is_currently_active
FROM offers o;
