-- =====================================================================
-- PHASE 2 — schema expansion (additive; no Phase 1 table is dropped or narrowed)
-- Modules: multi-branch/org, inventory, recipes, suppliers, purchasing, CRM, loyalty,
--          reservations, club entry, VIP tables, bottle service, room charges, notifications
-- =====================================================================
SET DEFINE OFF;

-- ---------------------------------------------------------------------
-- Organisation → Branch → Outlet
-- ---------------------------------------------------------------------
CREATE TABLE organizations (
  org_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_code             VARCHAR2(20)  NOT NULL,
  org_name             VARCHAR2(150) NOT NULL,
  plan_code            VARCHAR2(20)  DEFAULT 'STANDARD' NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_org_code UNIQUE (org_code),
  CONSTRAINT ck_org_status CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED'))
);
INSERT INTO organizations (org_id, org_code, org_name) VALUES (1, 'NEXOVO', 'Nexovo Hospitality');

ALTER TABLE branches ADD (
  org_id                    NUMBER DEFAULT 1 NOT NULL,
  stock_deduction_mode      VARCHAR2(20) DEFAULT 'ON_CONFIRM' NOT NULL,
  min_spend_shortfall_mode  VARCHAR2(20) DEFAULT 'CHARGE_DIFFERENCE' NOT NULL,
  min_spend_flat_fee        NUMBER(12,2) DEFAULT 0 NOT NULL,
  pms_provider              VARCHAR2(30) DEFAULT 'SIMULATED' NOT NULL,
  CONSTRAINT fk_branches_org FOREIGN KEY (org_id) REFERENCES organizations(org_id),
  CONSTRAINT ck_branches_sdm CHECK (stock_deduction_mode IN ('ON_CONFIRM','ON_BILL_CLOSE','MANUAL')),
  CONSTRAINT ck_branches_msm CHECK (min_spend_shortfall_mode IN ('CHARGE_DIFFERENCE','WAIVE','FLAT_FEE'))
);

CREATE TABLE outlets (
  outlet_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  outlet_code          VARCHAR2(20)  NOT NULL,
  outlet_name          VARCHAR2(100) NOT NULL,
  outlet_type          VARCHAR2(20)  DEFAULT 'RESTAURANT' NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_outlet_code UNIQUE (branch_id, outlet_code),
  CONSTRAINT fk_outlet_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_outlet_type CHECK (outlet_type IN ('RESTAURANT','BAR','CLUB','CAFE','LOUNGE','ROOM_SERVICE','BANQUET'))
);
ALTER TABLE floors ADD (outlet_id NUMBER, CONSTRAINT fk_floors_outlet FOREIGN KEY (outlet_id) REFERENCES outlets(outlet_id));

-- multi-branch access (SUPER_ADMIN bypasses)
CREATE TABLE user_branches (
  user_id              NUMBER NOT NULL,
  branch_id            NUMBER NOT NULL,
  is_default           CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT pk_user_branches PRIMARY KEY (user_id, branch_id),
  CONSTRAINT fk_ub_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_ub_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
);
INSERT INTO user_branches (user_id, branch_id, is_default) SELECT user_id, branch_id, 'Y' FROM users;

-- VIP table attributes
ALTER TABLE dining_tables ADD (
  is_vip               CHAR(1)      DEFAULT 'N' NOT NULL,
  min_spend_default    NUMBER(12,2) DEFAULT 0 NOT NULL,
  deposit_default      NUMBER(12,2) DEFAULT 0 NOT NULL,
  CONSTRAINT ck_tables_vip CHECK (is_vip IN ('Y','N'))
);

-- customer & bottle-service links on transactional tables
ALTER TABLE orders ADD (customer_id NUMBER, reservation_id NUMBER, club_entry_id NUMBER, vip_res_id NUMBER);
ALTER TABLE bills  ADD (customer_id NUMBER, loyalty_points_earned NUMBER(10) DEFAULT 0 NOT NULL, min_spend_shortfall NUMBER(12,2) DEFAULT 0 NOT NULL);
ALTER TABLE order_items ADD (is_bottle_service CHAR(1) DEFAULT 'N' NOT NULL, stock_deducted CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT ck_oi_bs CHECK (is_bottle_service IN ('Y','N')), CONSTRAINT ck_oi_sd CHECK (stock_deducted IN ('Y','N')));

-- ---------------------------------------------------------------------
-- Inventory
-- ---------------------------------------------------------------------
CREATE TABLE inventory_units (
  unit_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  unit_code            VARCHAR2(10)  NOT NULL,
  unit_name            VARCHAR2(40)  NOT NULL,
  base_unit_code       VARCHAR2(10)  NOT NULL,   -- unit family: G, ML, PIECE
  factor_to_base       NUMBER(14,6)  NOT NULL,   -- 1 unit = factor base units (KG → 1000 G)
  CONSTRAINT uq_unit_code UNIQUE (unit_code),
  CONSTRAINT ck_unit_factor CHECK (factor_to_base > 0)
);
-- explicit cross-family conversions (e.g. BOTTLE → ML for a specific item are kept on the item as pack_size)
CREATE TABLE unit_conversions (
  conversion_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  from_unit_id         NUMBER NOT NULL,
  to_unit_id           NUMBER NOT NULL,
  factor               NUMBER(14,6) NOT NULL,
  CONSTRAINT uq_unit_conv UNIQUE (from_unit_id, to_unit_id),
  CONSTRAINT fk_uc_from FOREIGN KEY (from_unit_id) REFERENCES inventory_units(unit_id),
  CONSTRAINT fk_uc_to   FOREIGN KEY (to_unit_id)   REFERENCES inventory_units(unit_id),
  CONSTRAINT ck_uc_factor CHECK (factor > 0)
);

CREATE TABLE inventory_categories (
  inv_cat_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  cat_name             VARCHAR2(80)  NOT NULL,
  cat_kind             VARCHAR2(20)  DEFAULT 'INGREDIENT' NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  CONSTRAINT uq_invcat UNIQUE (branch_id, cat_name),
  CONSTRAINT fk_invcat_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_invcat_kind CHECK (cat_kind IN ('INGREDIENT','RAW_MATERIAL','BEVERAGE','BOTTLE','PACKAGING','CONSUMABLE'))
);

CREATE TABLE suppliers (
  supplier_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  supplier_code        VARCHAR2(20)  NOT NULL,
  supplier_name        VARCHAR2(150) NOT NULL,
  contact_person       VARCHAR2(100),
  phone                VARCHAR2(30),
  email                VARCHAR2(150),
  address_line         VARCHAR2(400),
  gst_number           VARCHAR2(30),
  payment_terms_days   NUMBER(4)     DEFAULT 30 NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_supplier_code UNIQUE (branch_id, supplier_code),
  CONSTRAINT fk_supplier_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_supplier_status CHECK (status IN ('ACTIVE','INACTIVE','BLOCKED'))
);

CREATE TABLE inventory_items (
  inv_item_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  inv_cat_id           NUMBER        NOT NULL,
  item_code            VARCHAR2(30)  NOT NULL,
  item_name            VARCHAR2(150) NOT NULL,
  unit_id              NUMBER        NOT NULL,      -- stock-keeping unit (e.g. KG)
  pack_size            NUMBER(12,4),                -- optional: base units per PIECE/BOTTLE (750 ml bottle)
  current_qty          NUMBER(14,4)  DEFAULT 0 NOT NULL,
  min_qty              NUMBER(14,4)  DEFAULT 0 NOT NULL,
  max_qty              NUMBER(14,4),
  reorder_level        NUMBER(14,4)  DEFAULT 0 NOT NULL,
  cost_price           NUMBER(12,4)  DEFAULT 0 NOT NULL,   -- last purchase price per unit
  avg_cost             NUMBER(12,4)  DEFAULT 0 NOT NULL,   -- moving average per unit
  supplier_id          NUMBER,
  allow_negative       CHAR(1)       DEFAULT 'N' NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_invitem_code UNIQUE (branch_id, item_code),
  CONSTRAINT fk_invitem_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_invitem_cat FOREIGN KEY (inv_cat_id) REFERENCES inventory_categories(inv_cat_id),
  CONSTRAINT fk_invitem_unit FOREIGN KEY (unit_id) REFERENCES inventory_units(unit_id),
  CONSTRAINT fk_invitem_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
  CONSTRAINT ck_invitem_flags CHECK (allow_negative IN ('Y','N') AND is_active IN ('Y','N') AND is_deleted IN ('Y','N')),
  CONSTRAINT ck_invitem_qty CHECK (min_qty >= 0 AND reorder_level >= 0 AND cost_price >= 0 AND avg_cost >= 0)
);
CREATE INDEX ix_invitem_cat ON inventory_items (inv_cat_id);
CREATE INDEX ix_invitem_low ON inventory_items (branch_id, current_qty, min_qty);

-- Every stock change is a movement (never overwrite quantities directly)
CREATE TABLE stock_movements (
  mvt_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  inv_item_id          NUMBER        NOT NULL,
  mvt_type             VARCHAR2(20)  NOT NULL,
  qty                  NUMBER(14,4)  NOT NULL,      -- signed, in item unit (+in / -out)
  qty_before           NUMBER(14,4)  NOT NULL,
  qty_after            NUMBER(14,4)  NOT NULL,
  unit_cost            NUMBER(12,4)  DEFAULT 0 NOT NULL,
  total_cost           NUMBER(14,2)  DEFAULT 0 NOT NULL,
  ref_type             VARCHAR2(30),                -- ORDER_ITEM, GRN, PO, ADJUSTMENT …
  ref_id               NUMBER,
  idempotency_key      VARCHAR2(120),               -- e.g. ORDER_ITEM:123:DEDUCT — prevents double deduction/reversal
  reason               VARCHAR2(300),
  created_by           NUMBER,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_mvt_idem UNIQUE (idempotency_key),
  CONSTRAINT fk_mvt_item FOREIGN KEY (inv_item_id) REFERENCES inventory_items(inv_item_id),
  CONSTRAINT fk_mvt_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_mvt_type CHECK (mvt_type IN ('PURCHASE','SALE_CONSUMPTION','WASTAGE','DAMAGE','RETURN','TRANSFER','ADJUSTMENT','OPENING_STOCK','CONSUMPTION_REVERSAL'))
);
CREATE INDEX ix_mvt_item ON stock_movements (inv_item_id, created_at);
CREATE INDEX ix_mvt_branch ON stock_movements (branch_id, created_at);

-- ---------------------------------------------------------------------
-- Recipes (menu item → ingredients)
-- ---------------------------------------------------------------------
CREATE TABLE recipes (
  recipe_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  item_id              NUMBER        NOT NULL,
  variant_code         VARCHAR2(20)  DEFAULT 'STD' NOT NULL,   -- future: SMALL / LARGE / HALF
  portion_label        VARCHAR2(40)  DEFAULT 'Standard' NOT NULL,
  yield_qty            NUMBER(8,2)   DEFAULT 1 NOT NULL,       -- portions produced per recipe run
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_recipe_variant UNIQUE (item_id, variant_code),
  CONSTRAINT fk_recipe_item FOREIGN KEY (item_id) REFERENCES menu_items(item_id),
  CONSTRAINT ck_recipe_yield CHECK (yield_qty > 0)
);
CREATE TABLE recipe_items (
  recipe_item_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  recipe_id            NUMBER        NOT NULL,
  inv_item_id          NUMBER        NOT NULL,
  qty                  NUMBER(14,4)  NOT NULL,
  unit_id              NUMBER        NOT NULL,      -- may differ from stock unit (150 G of a KG item)
  wastage_pct          NUMBER(5,2)   DEFAULT 0 NOT NULL,
  CONSTRAINT fk_ri_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(recipe_id),
  CONSTRAINT fk_ri_item FOREIGN KEY (inv_item_id) REFERENCES inventory_items(inv_item_id),
  CONSTRAINT fk_ri_unit FOREIGN KEY (unit_id) REFERENCES inventory_units(unit_id),
  CONSTRAINT ck_ri_qty CHECK (qty > 0 AND wastage_pct BETWEEN 0 AND 100)
);
CREATE INDEX ix_ri_recipe ON recipe_items (recipe_id);

-- ---------------------------------------------------------------------
-- Purchasing
-- ---------------------------------------------------------------------
CREATE TABLE purchase_orders (
  po_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  po_number            VARCHAR2(30)  NOT NULL,
  branch_id            NUMBER        NOT NULL,
  supplier_id          NUMBER        NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'DRAFT' NOT NULL,
  expected_date        DATE,
  subtotal             NUMBER(14,2)  DEFAULT 0 NOT NULL,
  tax_total            NUMBER(14,2)  DEFAULT 0 NOT NULL,
  grand_total          NUMBER(14,2)  DEFAULT 0 NOT NULL,
  notes                VARCHAR2(500),
  sent_at              TIMESTAMP,
  approved_by          NUMBER,
  approved_at          TIMESTAMP,
  ordered_at           TIMESTAMP,
  received_at          TIMESTAMP,
  cancelled_at         TIMESTAMP,
  cancel_reason        VARCHAR2(300),
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_po_number UNIQUE (po_number),
  CONSTRAINT fk_po_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
  CONSTRAINT ck_po_status CHECK (status IN ('DRAFT','SENT','APPROVED','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED'))
);
CREATE INDEX ix_po_supplier ON purchase_orders (supplier_id, status);

CREATE TABLE purchase_order_items (
  po_item_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  po_id                NUMBER        NOT NULL,
  inv_item_id          NUMBER        NOT NULL,
  qty                  NUMBER(14,4)  NOT NULL,
  unit_id              NUMBER        NOT NULL,
  unit_price           NUMBER(12,4)  NOT NULL,
  tax_pct              NUMBER(5,2)   DEFAULT 0 NOT NULL,
  line_total           NUMBER(14,2)  NOT NULL,
  received_qty         NUMBER(14,4)  DEFAULT 0 NOT NULL,
  CONSTRAINT fk_poi_po FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id),
  CONSTRAINT fk_poi_item FOREIGN KEY (inv_item_id) REFERENCES inventory_items(inv_item_id),
  CONSTRAINT fk_poi_unit FOREIGN KEY (unit_id) REFERENCES inventory_units(unit_id),
  CONSTRAINT ck_poi_qty CHECK (qty > 0 AND unit_price >= 0 AND received_qty >= 0)
);
CREATE INDEX ix_poi_po ON purchase_order_items (po_id);

CREATE TABLE goods_receipts (
  grn_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  grn_number           VARCHAR2(30)  NOT NULL,
  po_id                NUMBER        NOT NULL,
  supplier_invoice_no  VARCHAR2(60),
  received_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  received_by          NUMBER        NOT NULL,
  total_amount         NUMBER(14,2)  DEFAULT 0 NOT NULL,
  notes                VARCHAR2(500),
  CONSTRAINT uq_grn_number UNIQUE (grn_number),
  CONSTRAINT fk_grn_po FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id),
  CONSTRAINT fk_grn_user FOREIGN KEY (received_by) REFERENCES users(user_id)
);
CREATE TABLE goods_receipt_items (
  grn_item_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  grn_id               NUMBER        NOT NULL,
  po_item_id           NUMBER        NOT NULL,
  inv_item_id          NUMBER        NOT NULL,
  received_qty         NUMBER(14,4)  NOT NULL,
  damaged_qty          NUMBER(14,4)  DEFAULT 0 NOT NULL,
  unit_cost            NUMBER(12,4)  NOT NULL,
  CONSTRAINT fk_gri_grn FOREIGN KEY (grn_id) REFERENCES goods_receipts(grn_id),
  CONSTRAINT fk_gri_poi FOREIGN KEY (po_item_id) REFERENCES purchase_order_items(po_item_id),
  CONSTRAINT ck_gri_qty CHECK (received_qty >= 0 AND damaged_qty >= 0)
);

CREATE TABLE supplier_payments (
  sp_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  supplier_id          NUMBER        NOT NULL,
  po_id                NUMBER,
  amount               NUMBER(14,2)  NOT NULL,
  method               VARCHAR2(20)  DEFAULT 'BANK' NOT NULL,
  reference_no         VARCHAR2(100),
  paid_at              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  notes                VARCHAR2(300),
  created_by           NUMBER,
  CONSTRAINT fk_sp_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
  CONSTRAINT fk_sp_po FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id),
  CONSTRAINT ck_sp_amount CHECK (amount > 0)
);

-- ---------------------------------------------------------------------
-- CRM & loyalty
-- ---------------------------------------------------------------------
CREATE TABLE customers (
  customer_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_id               NUMBER        DEFAULT 1 NOT NULL,
  full_name            VARCHAR2(150) NOT NULL,
  phone                VARCHAR2(30)  NOT NULL,
  email                VARCHAR2(150),
  birthday             DATE,
  anniversary          DATE,
  tags                 VARCHAR2(300),
  notes                VARCHAR2(500),
  consent_marketing    CHAR(1)       DEFAULT 'N' NOT NULL,   -- privacy: explicit opt-in only
  consent_at           TIMESTAMP,
  total_visits         NUMBER(8)     DEFAULT 0 NOT NULL,
  total_spend          NUMBER(14,2)  DEFAULT 0 NOT NULL,
  last_visit_at        TIMESTAMP,
  is_deleted           CHAR(1)       DEFAULT 'N' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_customer_phone UNIQUE (org_id, phone),
  CONSTRAINT fk_customer_org FOREIGN KEY (org_id) REFERENCES organizations(org_id),
  CONSTRAINT ck_customer_flags CHECK (consent_marketing IN ('Y','N') AND is_deleted IN ('Y','N'))
);
CREATE TABLE customer_visits (
  visit_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  customer_id          NUMBER        NOT NULL,
  branch_id            NUMBER        NOT NULL,
  order_id             NUMBER,
  bill_id              NUMBER,
  visited_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  amount               NUMBER(14,2)  DEFAULT 0 NOT NULL,
  CONSTRAINT fk_cv_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_cv_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_cv_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id)
);
CREATE INDEX ix_cv_customer ON customer_visits (customer_id, visited_at);
ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id);
ALTER TABLE bills  ADD CONSTRAINT fk_bills_customer  FOREIGN KEY (customer_id) REFERENCES customers(customer_id);

CREATE TABLE loyalty_programs (
  program_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_id               NUMBER        DEFAULT 1 NOT NULL,
  program_name         VARCHAR2(100) NOT NULL,
  points_per_100       NUMBER(8,2)   DEFAULT 10 NOT NULL,   -- ₹100 spent = N points
  point_value          NUMBER(8,4)   DEFAULT 1 NOT NULL,    -- 1 point = ₹ value on redemption
  min_redeem_points    NUMBER(8)     DEFAULT 100 NOT NULL,
  max_redeem_pct       NUMBER(5,2)   DEFAULT 50 NOT NULL,   -- max % of a bill payable by points
  expiry_days          NUMBER(5)     DEFAULT 365 NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  CONSTRAINT fk_lp_org FOREIGN KEY (org_id) REFERENCES organizations(org_id)
);
CREATE TABLE loyalty_accounts (
  account_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  customer_id          NUMBER        NOT NULL,
  program_id           NUMBER        NOT NULL,
  points_balance       NUMBER(12)    DEFAULT 0 NOT NULL,
  lifetime_points      NUMBER(12)    DEFAULT 0 NOT NULL,
  tier                 VARCHAR2(20)  DEFAULT 'SILVER' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_la_customer UNIQUE (customer_id),
  CONSTRAINT fk_la_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_la_program FOREIGN KEY (program_id) REFERENCES loyalty_programs(program_id),
  CONSTRAINT ck_la_balance CHECK (points_balance >= 0)
);
CREATE TABLE loyalty_transactions (
  ltx_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  account_id           NUMBER        NOT NULL,
  txn_type             VARCHAR2(20)  NOT NULL,
  points               NUMBER(12)    NOT NULL,      -- signed
  amount_ref           NUMBER(14,2),                -- bill amount (earn) or redeemed value
  bill_id              NUMBER,
  payment_id           NUMBER,
  ref_ltx_id           NUMBER,                      -- reversal → original
  notes                VARCHAR2(300),
  expires_at           TIMESTAMP,
  created_by           NUMBER,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_ltx_account FOREIGN KEY (account_id) REFERENCES loyalty_accounts(account_id),
  CONSTRAINT ck_ltx_type CHECK (txn_type IN ('EARN','REDEEM','EXPIRE','PROMO','REVERSAL'))
);
CREATE INDEX ix_ltx_account ON loyalty_transactions (account_id, created_at);

-- ---------------------------------------------------------------------
-- Reservations, club entry, VIP tables, bottle service
-- ---------------------------------------------------------------------
CREATE TABLE reservations (
  res_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  res_number           VARCHAR2(30)  NOT NULL,
  branch_id            NUMBER        NOT NULL,
  customer_id          NUMBER,
  guest_name           VARCHAR2(150) NOT NULL,
  phone                VARCHAR2(30)  NOT NULL,
  res_date             DATE          NOT NULL,
  res_time             VARCHAR2(5)   NOT NULL,      -- HH24:MI
  duration_min         NUMBER(4)     DEFAULT 120 NOT NULL,
  guests               NUMBER(4)     NOT NULL,
  table_pref           VARCHAR2(100),
  table_id             NUMBER,
  occasion             VARCHAR2(60),
  notes                VARCHAR2(500),
  status               VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
  deposit_amount       NUMBER(12,2)  DEFAULT 0 NOT NULL,
  seated_at            TIMESTAMP,
  order_id             NUMBER,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  updated_by           NUMBER,
  CONSTRAINT uq_res_number UNIQUE (res_number),
  CONSTRAINT fk_res_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_res_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_res_table FOREIGN KEY (table_id) REFERENCES dining_tables(table_id),
  CONSTRAINT fk_res_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT ck_res_status CHECK (status IN ('PENDING','CONFIRMED','SEATED','COMPLETED','CANCELLED','NO_SHOW')),
  CONSTRAINT ck_res_guests CHECK (guests > 0)
);
CREATE INDEX ix_res_date ON reservations (branch_id, res_date, res_time);

CREATE TABLE cover_charge_types (
  cover_type_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  cover_code           VARCHAR2(20)  NOT NULL,
  cover_name           VARCHAR2(80)  NOT NULL,
  amount               NUMBER(12,2)  NOT NULL,
  redeemable_amount    NUMBER(12,2)  DEFAULT 0 NOT NULL,   -- part of the cover usable against F&B
  guests_included      NUMBER(3)     DEFAULT 1 NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  CONSTRAINT uq_cover_code UNIQUE (branch_id, cover_code),
  CONSTRAINT fk_cover_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT ck_cover_amounts CHECK (amount >= 0 AND redeemable_amount >= 0 AND redeemable_amount <= amount)
);

CREATE TABLE club_entries (
  entry_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  entry_number         VARCHAR2(30)  NOT NULL,
  branch_id            NUMBER        NOT NULL,
  customer_id          NUMBER,
  guest_name           VARCHAR2(150) NOT NULL,
  phone                VARCHAR2(30),
  guests               NUMBER(4)     DEFAULT 1 NOT NULL,
  entry_type           VARCHAR2(20)  DEFAULT 'WALK_IN' NOT NULL,
  cover_type_id        NUMBER,
  cover_amount         NUMBER(12,2)  DEFAULT 0 NOT NULL,
  redeemable_amount    NUMBER(12,2)  DEFAULT 0 NOT NULL,
  redeemed_amount      NUMBER(12,2)  DEFAULT 0 NOT NULL,
  payment_method       VARCHAR2(20),
  host_user_id         NUMBER,
  table_id             NUMBER,
  status               VARCHAR2(20)  DEFAULT 'CHECKED_IN' NOT NULL,
  entered_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  exited_at            TIMESTAMP,
  notes                VARCHAR2(300),
  created_by           NUMBER,
  CONSTRAINT uq_entry_number UNIQUE (entry_number),
  CONSTRAINT fk_ce_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_ce_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_ce_cover FOREIGN KEY (cover_type_id) REFERENCES cover_charge_types(cover_type_id),
  CONSTRAINT fk_ce_host FOREIGN KEY (host_user_id) REFERENCES users(user_id),
  CONSTRAINT fk_ce_table FOREIGN KEY (table_id) REFERENCES dining_tables(table_id),
  CONSTRAINT ck_ce_type CHECK (entry_type IN ('WALK_IN','GUEST_LIST','PREBOOKED','VIP')),
  CONSTRAINT ck_ce_status CHECK (status IN ('CHECKED_IN','CHECKED_OUT','CANCELLED')),
  CONSTRAINT ck_ce_amounts CHECK (redeemed_amount >= 0 AND redeemed_amount <= redeemable_amount)
);
CREATE INDEX ix_ce_entered ON club_entries (branch_id, entered_at);

-- cover credit applied to a bill (payment method COVER_CREDIT)
CREATE TABLE club_entry_redemptions (
  redemption_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  entry_id             NUMBER        NOT NULL,
  bill_id              NUMBER        NOT NULL,
  payment_id           NUMBER        NOT NULL,
  amount               NUMBER(12,2)  NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_cer_entry FOREIGN KEY (entry_id) REFERENCES club_entries(entry_id),
  CONSTRAINT fk_cer_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
  CONSTRAINT fk_cer_payment FOREIGN KEY (payment_id) REFERENCES payments(payment_id)
);

CREATE TABLE vip_reservations (
  vip_res_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  vip_number           VARCHAR2(30)  NOT NULL,
  branch_id            NUMBER        NOT NULL,
  table_id             NUMBER        NOT NULL,
  customer_id          NUMBER,
  guest_name           VARCHAR2(150) NOT NULL,
  phone                VARCHAR2(30),
  res_date             DATE          NOT NULL,
  guests               NUMBER(4)     DEFAULT 1 NOT NULL,
  min_spend            NUMBER(12,2)  DEFAULT 0 NOT NULL,
  deposit_amount       NUMBER(12,2)  DEFAULT 0 NOT NULL,
  deposit_paid         CHAR(1)       DEFAULT 'N' NOT NULL,
  host_user_id         NUMBER,
  status               VARCHAR2(20)  DEFAULT 'BOOKED' NOT NULL,
  order_id             NUMBER,
  shortfall_amount     NUMBER(12,2)  DEFAULT 0 NOT NULL,   -- computed at billing
  notes                VARCHAR2(500),
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by           NUMBER,
  updated_at           TIMESTAMP,
  CONSTRAINT uq_vip_number UNIQUE (vip_number),
  CONSTRAINT fk_vip_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_vip_table FOREIGN KEY (table_id) REFERENCES dining_tables(table_id),
  CONSTRAINT fk_vip_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_vip_host FOREIGN KEY (host_user_id) REFERENCES users(user_id),
  CONSTRAINT fk_vip_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT ck_vip_status CHECK (status IN ('BOOKED','SEATED','COMPLETED','CANCELLED','NO_SHOW')),
  CONSTRAINT ck_vip_dep CHECK (deposit_paid IN ('Y','N'))
);
CREATE INDEX ix_vip_date ON vip_reservations (branch_id, res_date);

CREATE TABLE bottle_service_items (
  bs_item_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  item_id              NUMBER        NOT NULL,      -- the sellable menu item (e.g. Jack Daniels 750ml)
  bottle_size_ml       NUMBER(6)     NOT NULL,
  inv_item_id          NUMBER,                      -- stock bottle to deduct
  includes             VARCHAR2(500),               -- "Ice, 4 mixers, glasses, dedicated waiter"
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  CONSTRAINT uq_bs_item UNIQUE (item_id),
  CONSTRAINT fk_bs_item FOREIGN KEY (item_id) REFERENCES menu_items(item_id),
  CONSTRAINT fk_bs_inv FOREIGN KEY (inv_item_id) REFERENCES inventory_items(inv_item_id)
);

-- ---------------------------------------------------------------------
-- Hotel room charges (PMS integration abstraction)
-- ---------------------------------------------------------------------
CREATE TABLE room_charges (
  room_charge_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  bill_id              NUMBER        NOT NULL,
  payment_id           NUMBER,
  room_no              VARCHAR2(20)  NOT NULL,
  guest_name           VARCHAR2(150) NOT NULL,
  pms_provider         VARCHAR2(30)  NOT NULL,
  pms_reference        VARCHAR2(100),
  amount               NUMBER(12,2)  NOT NULL,
  status               VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
  posted_at            TIMESTAMP,
  failure_reason       VARCHAR2(300),
  created_by           NUMBER,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_rc_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
  CONSTRAINT fk_rc_payment FOREIGN KEY (payment_id) REFERENCES payments(payment_id),
  CONSTRAINT ck_rc_status CHECK (status IN ('PENDING','POSTED','FAILED','REVERSED'))
);

-- ---------------------------------------------------------------------
-- Notifications & thresholds
-- ---------------------------------------------------------------------
CREATE TABLE notifications (
  notif_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_id               NUMBER        DEFAULT 1 NOT NULL,
  branch_id            NUMBER,
  notif_type           VARCHAR2(40)  NOT NULL,      -- LOW_STOCK ORDER_DELAYED RESERVATION_REMINDER VIP_ARRIVAL LARGE_BILL_PENDING PO_APPROVAL …
  severity             VARCHAR2(10)  DEFAULT 'INFO' NOT NULL,
  title                VARCHAR2(150) NOT NULL,
  body                 VARCHAR2(500),
  entity_name          VARCHAR2(40),
  entity_id            NUMBER,
  target_role          VARCHAR2(30),                -- NULL = everyone in branch
  target_user_id       NUMBER,
  dedupe_key           VARCHAR2(120),               -- suppress duplicates while unresolved
  is_read              CHAR(1)       DEFAULT 'N' NOT NULL,
  read_at              TIMESTAMP,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_notif_sev CHECK (severity IN ('INFO','WARNING','CRITICAL')),
  CONSTRAINT ck_notif_read CHECK (is_read IN ('Y','N'))
);
CREATE INDEX ix_notif_branch ON notifications (branch_id, is_read, created_at);
CREATE INDEX ix_notif_dedupe ON notifications (dedupe_key);

CREATE TABLE notification_logs (
  log_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  notif_id             NUMBER        NOT NULL,
  channel              VARCHAR2(20)  NOT NULL,      -- IN_APP WHATSAPP SMS EMAIL PUSH
  provider             VARCHAR2(40),
  status               VARCHAR2(20)  NOT NULL,      -- QUEUED SENT FAILED
  response             VARCHAR2(500),
  sent_at              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_nl_notif FOREIGN KEY (notif_id) REFERENCES notifications(notif_id)
);

CREATE TABLE alert_thresholds (
  threshold_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  branch_id            NUMBER        NOT NULL,
  threshold_key        VARCHAR2(40)  NOT NULL,      -- ORDER_DELAY_MIN KITCHEN_BACKLOG BAR_BACKLOG BILL_PENDING_MIN LARGE_BILL_AMOUNT
  threshold_value      NUMBER(12,2)  NOT NULL,
  is_active            CHAR(1)       DEFAULT 'Y' NOT NULL,
  CONSTRAINT uq_threshold UNIQUE (branch_id, threshold_key),
  CONSTRAINT fk_thr_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
);

-- ---------------------------------------------------------------------
-- Views
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW v_inventory_status AS
SELECT i.inv_item_id, i.branch_id, i.item_code, i.item_name, c.cat_name, c.cat_kind, u.unit_code,
       i.current_qty, i.min_qty, i.reorder_level, i.avg_cost, i.current_qty * i.avg_cost AS stock_value,
       CASE WHEN i.current_qty <= 0 THEN 'OUT' WHEN i.current_qty <= i.min_qty THEN 'LOW' WHEN i.current_qty <= i.reorder_level THEN 'REORDER' ELSE 'OK' END AS stock_status
FROM inventory_items i JOIN inventory_categories c ON c.inv_cat_id = i.inv_cat_id JOIN inventory_units u ON u.unit_id = i.unit_id
WHERE i.is_deleted = 'N' AND i.is_active = 'Y';

CREATE OR REPLACE VIEW v_supplier_balance AS
SELECT s.supplier_id, s.branch_id,
       NVL((SELECT SUM(g.total_amount) FROM goods_receipts g JOIN purchase_orders p ON p.po_id = g.po_id WHERE p.supplier_id = s.supplier_id), 0) AS total_received_value,
       NVL((SELECT SUM(sp.amount) FROM supplier_payments sp WHERE sp.supplier_id = s.supplier_id), 0) AS total_paid
FROM suppliers s;
